from enum import Enum


class ApiSubmissionOption(str, Enum):
    ITEM_SUBMISSION = "ITEM_SUBMISSION"
    LIMIT_CORRECT_PER_MEMBER = "LIMIT_CORRECT_PER_MEMBER"
    LIMIT_CORRECT_PER_TEAM = "LIMIT_CORRECT_PER_TEAM"
    LIMIT_TOTAL_PER_TEAM = "LIMIT_TOTAL_PER_TEAM"
    LIMIT_WRONG_PER_TEAM = "LIMIT_WRONG_PER_TEAM"
    MINIMUM_TIME_GAP = "MINIMUM_TIME_GAP"
    NO_DUPLICATES = "NO_DUPLICATES"
    TEMPORAL_SUBMISSION = "TEMPORAL_SUBMISSION"
    TEXTUAL_SUBMISSION = "TEXTUAL_SUBMISSION"

    def __str__(self) -> str:
        return str(self.value)
